name: probashtotthokandro
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  cloud_firestore: ^3.1.8
  # cloud_firestore_web: ^2.6.8
  get: 4.6.1
  marquee: ^2.2.1
  youtube_player_flutter: ^8.0.0
  flutter_inappwebview: ^5.3.2
  url_launcher: ^6.0.20
  font_awesome_flutter: ^9.2.0

  flutter:
    sdk: flutter
  firebase: ^9.0.2

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
